"""31 ->32

Revision ID: 22991c80ed08
Revises: 3e45f4e058a2
Create Date: 2018-07-27 22:49:20.955412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22991c80ed08'
down_revision = '3e45f4e058a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('field', sa.String(length=128), nullable=True))
    op.add_column('company_detail', sa.Column('finance_stage', sa.String(length=128), nullable=True))
    op.drop_index('ix_company_detail_slug', table_name='company_detail')
    op.drop_column('company_detail', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('slug', mysql.VARCHAR(length=24), nullable=False))
    op.create_index('ix_company_detail_slug', 'company_detail', ['slug'], unique=True)
    op.drop_column('company_detail', 'finance_stage')
    op.drop_column('company_detail', 'field')
    # ### end Alembic commands ###
