"""add user.is.disable

Revision ID: b08e719d345d
Revises: 1bb4c860e727
Create Date: 2018-07-30 22:04:09.079201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08e719d345d'
down_revision = '1bb4c860e727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_disable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_disable')
    # ### end Alembic commands ###
