"""add job description

Revision ID: f9ff0289db94
Revises: b08e719d345d
Create Date: 2018-08-01 12:24:24.849488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ff0289db94'
down_revision = 'b08e719d345d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('description', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'description')
    # ### end Alembic commands ###
